### ISSUE TITLE
[React] Column pinning to the right does not work

### ISSUE THREAD

**Issue by IMinchev64** [IgniteUI/igniteui-xplat-examples#728]
Go to [this sample](https://www.infragistics.com/react-demos/grids/grid/column-pinning-right-side) and see how even though the pinning config specifies that the pinned columns should be on the right (end) they are still on the left as they are by default.

This could potentially be a product issue which would need to be logged separately and fixed or the topic section might need to be removed.

**Comment by IMinchev64** [comment]
Logged a separate issue [here ](https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/34678) which is resolved for React by [this PR](https://infragistics.visualstudio.com/NetAdvantage/_git/eded35d7-efa9-46e9-86b0-65a256568bb6/pullrequest/14325)

**Comment by MayaKirova** [comment]
Works with newer versions i.e.:
 "igniteui-react-grids": "18.8.0",

However staging and live are still not updated.
